### ISSUE TITLE
希望連結資源可以上傳google雲端或dropbox

### ISSUE THREAD

**Issue by leeivan1007** [redtreeai/super-flying-chess#2]
百度不開放給台灣下載資源，但感覺整個架構很猛，希望有機會也能嘗試玩玩，感謝！

**Comment by redtreeai** [comment]
台湾的朋友你好～ ，谢谢支持。 后续会提供相应的下载资源。打算和加入AI的版本一起上传。

**Comment by leeivan1007** [comment]
哦哦謝謝！AI版本是指人工智慧的reinforcement learning嗎？還是普通的AI機器人判斷？如果是後者，我這可盡微薄之力提供這方面貢獻XD

**Comment by redtreeai** [comment]
hi ~  我发布了加入 easy_ai的版本。现在的ai只是随机行动，并没有智慧和策略。如果你有兴趣加入的话，可以先看下源码，我已经标注了可以加入ai策略的模块。目前的话还是以普通的机器人脚本判断方式为主。
=============================
关于资源下载，我发布在了坚果云，不知道台湾能不能使用。 google和dropbox实在传不上去，网络太差了。后面看看能不能代理发布

**Comment by leeivan1007** [comment]
好，感謝你！我這禮拜比較忙，下個禮拜來研究。 阿阿抱歉突然想到百度雲也可以！ 堅果雲我會再試試看，太感謝你了XD
